# Семинар 1: знакомство с NumPy


## Немного про Jupyter notebook

Полная документация: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

---
В Jupyter Notebook есть два режима работы: режим _команд_ и режим _редактирования_

_Командный_ режим нужен для того, чтобы взаимодействовать и управлять ячейками (добавлять, удалять, запускать, копировать, ...)

В режиме _редактирования_ вы меняете содержимое ячейки.

Ячейки бывают двух основных типов, _код_ и _разметка_

### Полезные команды

(находясь в командном режиме)

- `a` - добавить пустую ячейку сверху

- `b` - добавить пустую ячейку снизу
- `c` - скопировать текущую ячейку
- `v` - вставить скопированную ячейку
- `d` - удалить текущую ячейку
- `x` - вырезать (удалить и скопировать) текущую ячейку
- `m` - изменить тип выбранной ячейки на "разметка"
- `y` - изменить тип выбранной ячейки на "код"
- `z` - отменить последнее действие


- `Enter` - начать редактировать выбранную ячейку

(будучи в режим редактирования ячейки)
- `esc` - вернуться в командный режим

(будучи в любом режиме)

- `Ctrl + Enter` - запустить выбранную ячейку
- `Shift + Enter` - запустить выбранную ячейку и выбрать следующую

In [ ]:
2 + 2

5

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [1]:
import numpy as np

In [2]:
v = [[1, 2], [3, 4], [5, 6]]

In [3]:
type(v)

list

In [24]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [5]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
type(vec)

numpy.ndarray

In [6]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [ ]:
vec.dtype

In [ ]:
type(vec)

In [8]:
v * 2

[[1, 2], [3, 4], [5, 6], [1, 2], [3, 4], [5, 6]]

In [9]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [11]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [12]:
vec @ vec.T

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

Размер массива:

In [13]:
vec.shape

(3, 2)

In [14]:
vec.T.shape

(2, 3)

In [15]:
(vec @ vec.T).shape

(3, 3)

In [18]:
vec.dot(vec.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [19]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
help(vec)

In [ ]:
dir(vec)

Число осей:

In [20]:
vec.ndim

2

In [25]:
vec.dtype

dtype('int64')

In [26]:
type(4)

int

In [27]:
type(4.)

float

In [28]:
4. == 4.0

True

In [29]:
1 - 0.9 == 0.1

False

In [30]:
1 - 0.9

0.09999999999999998

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [32]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
np.sum(vec)

21

In [33]:
np.sum(vec, axis=0)

array([ 9, 12])

In [35]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [36]:
vec.sum()

21

Транспонируем массив:

In [37]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [38]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [39]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
s = 'abc'

In [42]:
s[1] = 'd'

TypeError: 'str' object does not support item assignment

In [44]:
l = [1, 2, 3]

In [45]:
l[1] = 10

In [46]:
l

[1, 10, 3]

In [47]:
id(l)

136346118550336

In [48]:
l[2] = 4

In [49]:
l

[1, 10, 4]

In [50]:
id(l)

136346118550336

Размеры массивов можно менять:

In [54]:
vec1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 12])

In [56]:
vec1.reshape(-1, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  1, 12]])

In [57]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
vec.reshape(6, -1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [61]:
vec.reshape(-1, 6)

array([[1, 2, 3, 4, 5, 6]])

Индексирование:

In [62]:
l = [1, 2, 3, 4, 5]

In [63]:
start = 1
stop = 3
step = 1

In [64]:
l[start:stop:step]

[2, 3]

In [65]:
l[::-1]

[5, 4, 3, 2, 1]

In [67]:
l[4:1:-1]

[5, 4, 3]

In [ ]:
vec[:, 1]

In [ ]:
vec[2, :]

In [ ]:
vec[1:2, 0]

In [69]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
vec[::2, ::-1]

array([[2, 1],
       [6, 5]])

И, наконец - арифметические операции!

In [71]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [72]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [73]:
vec**2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [74]:
vec + vec**2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [75]:
vec + vec

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [76]:
vec * vec**2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [77]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [78]:
vec.dot(vec**2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [79]:
vec.dot((vec**2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [80]:
vec @ (vec**2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [81]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [82]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [83]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Булевы массивы:

In [85]:
3 % 2

1

In [86]:
4 % 2

0

In [87]:
vec % 2

array([[1, 0],
       [1, 0],
       [1, 0]])

In [88]:
vec % 2 == 0

array([[False,  True],
       [False,  True],
       [False,  True]])

In [84]:
is_even = (vec % 2 == 0)
print(is_even)

[[False  True]
 [False  True]
 [False  True]]


In [89]:
np.sum(is_even)

3

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [90]:
vec[vec % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [91]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [92]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [93]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [94]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [95]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [96]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Генерация случайных чисел:

In [97]:
np.random.rand(2, 3)

array([[0.25517878, 0.07898633, 0.08779205],
       [0.34393702, 0.7469879 , 0.08959037]])

In [98]:
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [99]:
np.random.randn(3, 2)

array([[ 0.57376143,  0.28772767],
       [-0.23563426,  0.95349024],
       [-1.6896253 , -0.34494271]])

In [ ]:
np.random.normal(2, 1, size=3)

In [ ]:
np.random.randint(5, 10, size=3)

Почему вообще используют `numpy`?

In [100]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [101]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: user 27.6 s, sys: 639 µs, total: 27.6 s
Wall time: 28.3 s


In [102]:
%%time
C = A @ B

CPU times: user 8.18 ms, sys: 0 ns, total: 8.18 ms
Wall time: 19.1 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [ ]:
# ┌(▼▼メ)┘ └(メ▼▼)┐